#!/bin/bash

echo "============================================"
echo "🚀 ADICIONAR DATABASE_URL NA VERCEL"
echo "============================================"
echo ""
echo "1. Acesse: https://vercel.com/dashboard"
echo "2. Projeto: advisior-cursor"
echo "3. Settings → Environment Variables → Add New"
echo ""
echo "Key: DATABASE_URL"
echo ""
echo "Value (copie):"
echo "postgresql://neondb_owner:npg_nOTlR6gMra9G@ep-quiet-shape-addtxqaq-pooler.c-2.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
echo ""
echo "Environments: Production + Preview + Development"
echo ""
echo "4. Save"
echo "5. Aguardar redeploy (~2 min)"
echo "6. Me avisar!"
echo ""
echo "============================================"
